version: '3.1'

services:

  some-mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: admin
    ports: 
      - 3307:3306
  
  some-prestashop:
    container_name: some-prestashop
    image: prestashop/prestashop
    environment: 
      DB_SERVER: some-mysql
    ports: 
      - 80:80