version: '3.1'

services:

  bookmedik:
    container_name: bookmedik
    image: jose20035/bookmedik:php
    restart: always
    environment: 
      USER: bookmedik
      PASS: bookmedik
      NOMBRESQL: db
      NOMBREDB: bookmedik
    ports: 
      - 80:80
    volumes:
      - /VContenedores/log_apache2:/var/log/apache2
  
  db:
    container_name: MariaDB
    image: mariadb
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bookmedik
      MYSQL_PASSWORD: bookmedik
      MYSQL_DATABASE: bookmedik
    volumes: 
      - /VContenedores/DB:/var/lib/mysql